### ISSUE TITLE
Tuple Unpacking Error

### ISSUE THREAD

**Issue by jamesmcclain** [AdeelH/pytorch-fpn#1]
I am getting an error on [this line](https://github.com/AdeelH/pytorch-fpn/blob/6a733a4b3b77ec2b1fb04f5c1feabcabd525f00f/containers.py#L89).  It seems that sometimes `inps` is a tuple of four rather than the expect two.  I am using this with the last pre-nochip version of raster vision.

**Comment by AdeelH** [comment]
Can you share the stack trace? Also, in the meanwhile, as a workaround, you can use the 0.1 release.

**Comment by jamesmcclain** [comment]
> Can you share the stack trace? Also, in the meanwhile, as a workaround, you can use the 0.1 release.

Yeah, I am currently using the 0.1 release.  I'll try to capture the stack trace shortly.

**Comment by AdeelH** [comment]
Nevermind. I was able to reproduce it. Working on a fix.
