### ISSUE TITLE
Fusion Process Assumes Location of RGB Channels

### ISSUE THREAD

**Issue by jamesmcclain** [AdeelH/pytorch-fpn#2]
The fusion process [here](https://github.com/AdeelH/pytorch-fpn/blob/98c2ea43a9b0118c2e1dc29497bf6c832da5706b/factory.py#L79-L87) seems to assume that the RGB channels are the first three channels of the input (that is, the 3 channels from the pretrained input layer are always matched with the first three channels of the input).

**Comment by AdeelH** [comment]
This is intentional. The documentation should state this assumption explicitly though. Thanks for the catch.

**Comment by jamesmcclain** [comment]
> This is intentional. The documentation should state this assumption explicitly though. Thanks for the catch.

:ok_hand:
